### ISSUE TITLE
Backport of PR#9 to CMSSW_12_3_0

### ISSUE THREAD

**Issue by elfontan** [cms-data/L1Trigger-L1TGlobal#10]
An **updated full set of xml files for the L1 emulation of prescales and masks coherent with the updated v1_0_0 L1 menu** for Run 3 is provided in https://github.com/cms-data/L1Trigger-L1TGlobal/pull/9. 
I would like to ask for the backport of the PR to **CMSSW_12_3_0** in order to have a coherent set of menu and PS+mask tables in the release.

**Comment by aandvalenzuela** [comment]
Sure @elfontan! Changes will be backported to _CMSSW_12_3_0_ in [PR #7770](https://github.com/cms-sw/cmsdist/pull/7770) once it passes the tests.

Many thanks,
Andrea.

**Comment by elfontan** [comment]
Thank you!
